import '../scss/mobile_menu.scss'
import '../scss/request.scss'
import '../scss/style.scss'
import '../scss/header.scss'
import '../scss/contacts.scss'
import '../scss/reset.scss'
import '../scss/menu_button.scss'
import '../scss/body__mobileMenu.scss'
import '../scss/title.scss'
import '../scss/navigation.scss'
import '../scss/description.scss'
import '../scss/search-button.scss'
import '../scss/menu-mobile.scss'
import '../scss/menu-mobile-footer.scss'
import '../scss/swiper.scss'
import '../scss/slider-repair.scss'
import '../scss/slider-price.scss'
import '../scss/comercial-block.scss'
import '../scss/footer.scss'
import '../scss/button-order.scss'
import '../scss/table-price.scss'
import '../scss/popup-request.scss'
import '../scss/overlay.scss'
import '../scss/button-style.scss'

import '../js/mobile_menu.js'
import '../js/view_all.js'
import '../js/swiper.js'
import '../js/popup-call.js'


console.log('Works!')
